###
# @name getAllUsers
GET http://localhost:8080/api/v1/users
Authorization: Bearer {{auth_token}}

###
# @name getUserById
GET http://localhost:8080/api/v1/users/1
Authorization: Bearer {{auth_token}}

###
# @name signup
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "name": "Alex",
  "email": "alex@alex.net",
  "password": "12345678",
  "role": "USER"
}

###
# @name login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "identifier": "Alex",
  "password": "12345678"
}

### Verify and save token
# @name verify
POST http://localhost:8080/api/v1/auth/verify
Content-Type: application/json

{
  "identifier": "Alex",
  "code": "868699"
}

> {%
    client.global.set("auth_token", response.body.data.authToken);
%}

###
# @name update(put)
PUT http://localhost:8080/api/v1/users/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Alex",
  "email": "alex@alex.net",
  "password": "12345678",
  "role": "USER"
}

###
# @name update (patch)
PATCH http://localhost:8080/api/v1/users/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Aleksei"
}

###
# @name delete
DELETE http://localhost:8080/api/v1/users/1
Authorization: Bearer {{auth_token}}

###