###
# @name signup
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "name": "James Bond",
  "email": "a.gedz@silport.ee",
  "password": "12345678",
  "role": "USER"
}

###
# @name login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "identifier": "James Bond",
  "password": "12345678"
}

### Verify and save token
# @name verify
POST http://localhost:8080/api/auth/verify
Content-Type: application/json

{
  "identifier": "James Bond",
  "code": "597128"
}

> {%
    client.global.set("auth_token", response.body.data.authToken);
%}

###
# @name getCurrentUser
GET http://localhost:8080/api/user/current
Authorization: Bearer {{auth_token}}

###
# @name getAllUsers only for ADMIN
GET http://localhost:8080/api/users
Authorization: Bearer {{auth_token}}

###
# @name getUserById
GET http://localhost:8080/api/user/1
Authorization: Bearer {{auth_token}}

###
# @name update(put)
PUT http://localhost:8080/api/user/2
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Aleksei",
  "email": "alex@alex.net",
  "password": "12345678",
  "role": "USER"
}

###
# @name update (patch)
PATCH http://localhost:8080/api/user/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Aleksei"
}

###
# @name delete
DELETE http://localhost:8080/api/user/2
Authorization: Bearer {{auth_token}}

###