server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

  config:
    import:
      - optional:classpath:.env[.properties]
  application:
    name: rest_api
  datasource:
    url: jdbc:h2:file:./data/rest_api;AUTO_SERVER=TRUE
    username: rest_user
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    #  jpa:
    #    hibernate:
    #      ddl-auto: update
    properties.hibernate.format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USR}
    password: ${EMAIL_PWD}
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true

jwtSecret: ${JWT_SECRET}
jwtExpirationMs: ${JWT_EXP}
redirectVerifyUrl: http://localhost:4200/verify?identifier=
githubEmailApi: https://api.github.com/user/emails
resetPassword: http://localhost:4200/forgot-password?token=
app:
  cors:
    allowed-origins:
      - http://localhost:4200
rate-limit:
  capacity: 10
  refill-minutes: 1

